version: "3"

services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "8000"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME = postgres
      - SPRING_DATASOURCE_PASSWORD = inesmartins
      - SPRING_JPA_HIBERNATE_DDL_AUTO =update
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = inesmartins